# Generated by Django 4.2.7 on 2023-11-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='_'),
            preserve_default=False,
        ),
    ]
